services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
        - json_storage:/app/storage
volumes:
  json_storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage